package water_billing_platform.service;

import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import water_billing_platform.entity.Household;
import water_billing_platform.entity.Notification;
import water_billing_platform.repository.HouseholdRepository;
import water_billing_platform.repository.NotificationRepository;

import java.time.LocalDate;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;

@Service
@RequiredArgsConstructor
public class NotificationService {

    private final NotificationRepository notificationRepository;
    private final HouseholdRepository householdRepository;

    // =========================================================
    // CREATE NOTIFICATION
    // =========================================================

    public Notification createNotification(Notification notification) {

        if (notification.getTitle() == null ||
                notification.getTitle().trim().isEmpty()) {

            throw new RuntimeException(
                    "Notification title is required."
            );
        }

        if (notification.getMessage() == null ||
                notification.getMessage().trim().isEmpty()) {

            throw new RuntimeException(
                    "Notification message is required."
            );
        }

        if (notification.getNotificationType() == null ||
                notification.getNotificationType().trim().isEmpty()) {

            notification.setNotificationType("GENERAL");
        }

        /*
         * Created date is always generated by backend.
         * Frontend does not need to send it.
         */
        notification.setCreatedDate(LocalDate.now());

        return notificationRepository.save(notification);
    }

    // =========================================================
    // GET NOTIFICATIONS FOR HOUSEHOLD
    // =========================================================

    public List<Notification> getNotificationsForHousehold(
            Long householdId) {

        Household household =
                householdRepository
                        .findById(householdId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Household not found: "
                                                + householdId
                                )
                        );

        /*
         * Notifications specifically sent to this household
         */
        List<Notification> targeted =
                notificationRepository
                        .findByHouseholdIdOrderByCreatedDateDesc(
                                householdId
                        );

        /*
         * Notifications sent to the complete apartment
         */
        List<Notification> broadcast =
                notificationRepository
                        .findByApartmentIdOrderByCreatedDateDesc(
                                household
                                        .getApartment()
                                        .getId()
                        );

        /*
         * Combine both notification types.
         */
        return Stream.concat(
                        targeted.stream(),
                        broadcast.stream()
                )
                .distinct()
                .sorted(
                        (a, b) ->
                                b.getCreatedDate()
                                        .compareTo(
                                                a.getCreatedDate()
                                        )
                )
                .collect(Collectors.toList());
    }

    // =========================================================
    // GET SENT NOTIFICATIONS FOR APARTMENT
    // =========================================================

    public List<Notification> getSentForApartment(
            Long apartmentId) {

        return notificationRepository
                .findByApartmentIdOrderByCreatedDateDesc(
                        apartmentId
                );
    }

    // =========================================================
    // GET SINGLE NOTIFICATION
    // =========================================================

    public Notification getNotificationById(Long id) {

        return notificationRepository
                .findById(id)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Notification not found: " + id
                        )
                );
    }

    // =========================================================
    // DELETE NOTIFICATION
    // =========================================================

    public void deleteNotification(Long id) {

        if (!notificationRepository.existsById(id)) {

            throw new RuntimeException(
                    "Notification not found: " + id
            );
        }

        notificationRepository.deleteById(id);
    }
}