ALTER TABLE apartments ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE apartments ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE apartments ADD COLUMN deleted_by VARCHAR(255);

ALTER TABLE users ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE users ADD COLUMN deleted_by VARCHAR(255);

ALTER TABLE households ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE households ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE households ADD COLUMN deleted_by VARCHAR(255);

ALTER TABLE bills ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE bills ADD COLUMN deleted_at TIMESTAMP;
ALTER TABLE bills ADD COLUMN deleted_by VARCHAR(255);