ALTER TABLE payments ADD COLUMN collected_by VARCHAR(255);
ALTER TABLE payments ADD COLUMN remarks VARCHAR(500);
ALTER TABLE payments ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'PAID';
ALTER TABLE bills ADD COLUMN due_date DATE;
