spring.application.name=water-billing-platform

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/water_billing_db}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:1911}

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com

spring.mail.port=587

spring.mail.username=kishorkishukp18@gmail.com

spring.mail.password=kgtl nkrh fkcp mbyh

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.properties.mail.smtp.connectiontimeout=10000

spring.mail.properties.mail.smtp.timeout=10000

spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

razorpay.key.id=rzp_test_TLh4oaO1P4AvKk

razorpay.key.secret=DhJQfPLAQZZYHMfBc32GMUVp